[package]
name = "wec"
version = "0.1.0"
edition = "2021"
authors = ["Maria José Solano <majosolano99@gmail.com>"]
categories = ["development-tools"]
keywords = ["macros"]
readme = "README.md"

[dev-dependencies]
pretty_assertions = "1.3.0"
trybuild = "1.0.80"
